### ISSUE TITLE
Ninja needs to have a basic attack

### ISSUE THREAD

**Issue by BadassBison** [BadassBison/Bokudos#27]
As a player, I need to have a basic attack with my ninja. 

Acceptance:

- This attack needs to happen when the ninja is standing still. 
- This attack needs to have a key input to trigger the attack
- The correct animation is displayed when the attack happens
- There needs to be detection over the area that the ninja is attacking to determine if there was a hit

**Comment by BadassBison** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ninja attack animation](https://trello.com/c/p4BwjHEd/3-ninja-attack-animation)

**Comment by codymaki** [comment]
Closing this issue, the attack hit detection part has been moved to a separate issue. https://github.com/BadassBison/Bokudos/issues/40
