### ISSUE TITLE
Ninja needs a jumping attack

### ISSUE THREAD

**Issue by BadassBison** [BadassBison/Bokudos#28]
As a player, I need the ability to jump and attack

Acceptance

- This attack uses the same key as the basic attack
- This attack uses the same detection of the basic attack
- The Jumping animation only happens while the ninja is in the air

**Comment by BadassBison** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ninja jump attack animation](https://trello.com/c/ugn8uQ5X/4-ninja-jump-attack-animation)

**Comment by codymaki** [comment]
Closing this issue, the attack hit detection part has been moved to a separate issue. https://github.com/BadassBison/Bokudos/issues/40
